### ISSUE TITLE
Add "Saved" conjurations filter

### ISSUE THREAD

**Issue by zurfluha** [Bitmischief/mythweaver#158]
As a user I want to get only my conjurations, saved conjurations, or all conjurations.

**Comment by UnknownStranger** [comment]
Rough mock idea that could allow for filtering by all, personal or bookmarked, or personal and bookmarked. 
TL;DR select dropdown, or checkbox/toggles in the long run? Options abound.
![image](https://github.com/Bitmischief/mythweaver/assets/11340899/6f64ff85-f152-456f-aa59-74726ba4a00d)
